<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless"/>
    <PackageReference Include="Avalonia.Headless.XUnit"/>
    <PackageReference Include="xunit.v3"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Irihi.Dogma\Irihi.Dogma.csproj"/>
  </ItemGroup>

</Project>
