<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"/>
    <PackageReference Include="Avalonia.Desktop"/>
    <PackageReference Include="Avalonia.Themes.Fluent"/>
    <PackageReference Include="CommunityToolkit.Mvvm"/>
    <PackageReference Include="Irihi.Lingua"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Irihi.Dogma\Irihi.Dogma.csproj"/>
    <ProjectReference Include="..\..\src\Irihi.Dogma.Docs.Generator\Irihi.Dogma.Docs.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>

  <ItemGroup>
    <!-- Lingua 资源 -->
    <AdditionalFiles Include="Resources\**\*.resx"/>
  </ItemGroup>

</Project>
