<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Irihi Technology</Authors>
    <RepositoryUrl>https://github.com/irihitech/Irihi.Dogma</RepositoryUrl>
    <PackageProjectUrl>https://github.com/irihitech/Irihi.Dogma</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>0.2.3</Version>
  </PropertyGroup>
</Project>
